[WHAT IS PYTORCH?](https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html#sphx-glr-beginner-blitz-tensor-tutorial-py)

## 入门

### 张量 Tensor
张量类似于NumPy的ndarray，另外还有Tensors也可用于GPU以加速计算

In [1]:
from __future__ import print_function
import torch

构造一个初始化的5x3 矩阵：

In [2]:
x=torch.empty(5,3)
print(x)

tensor([[5.7858e-39, 8.4490e-39, 5.3266e-39],
        [7.3470e-39, 1.0194e-38, 9.2755e-39],
        [1.0653e-38, 1.0378e-38, 9.6429e-39],
        [9.0919e-39, 4.1328e-39, 1.1112e-38],
        [9.5511e-39, 1.0102e-38, 3.8572e-39]])


创建一个随机初始化的矩阵

In [7]:
x=torch.rand(5,3)
print(x)

tensor([[0.6368, 0.7244, 0.2436],
        [0.4372, 0.7837, 0.3431],
        [0.2522, 0.0893, 0.1554],
        [0.9334, 0.1508, 0.2978],
        [0.3199, 0.0262, 0.9431]])


创建一个0矩阵，数据类型为long

In [11]:
x=torch.zeros(5,3,dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


直接根据数据创建张量

In [12]:
x=torch.tensor([5.5,3])
print(x)

tensor([5.5000, 3.0000])


根据已有张量创建张量

In [13]:
x=x.new_ones(5,3,dtype=torch.double)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [15]:
x=torch.rand_like(x,dtype=torch.float)
print(x)

tensor([[0.3496, 0.8427, 0.1208],
        [0.4682, 0.4661, 0.2342],
        [0.5087, 0.6920, 0.4003],
        [0.8069, 0.2325, 0.7005],
        [0.1433, 0.4009, 0.4064]])


输出矩阵大小

In [16]:
print(x.size())

torch.Size([5, 3])


### 张量运算

In [26]:
x

tensor([[0.3496, 0.8427, 0.1208],
        [0.4682, 0.4661, 0.2342],
        [0.5087, 0.6920, 0.4003],
        [0.8069, 0.2325, 0.7005],
        [0.1433, 0.4009, 0.4064]])

In [20]:
## 加法 1
y=torch.rand(5,3)
print(x+y)

tensor([[1.1852, 1.0870, 0.7054],
        [0.5820, 1.3569, 0.4054],
        [0.6848, 1.4990, 0.5285],
        [1.5548, 1.0458, 0.8686],
        [1.0402, 0.8104, 1.2504]])


In [21]:
## 加法 2
print(torch.add(x,y))

tensor([[1.1852, 1.0870, 0.7054],
        [0.5820, 1.3569, 0.4054],
        [0.6848, 1.4990, 0.5285],
        [1.5548, 1.0458, 0.8686],
        [1.0402, 0.8104, 1.2504]])


In [22]:
## 赋值
result=torch.empty(5,3)
torch.add(x,y,out=result)
print(result)

tensor([[1.1852, 1.0870, 0.7054],
        [0.5820, 1.3569, 0.4054],
        [0.6848, 1.4990, 0.5285],
        [1.5548, 1.0458, 0.8686],
        [1.0402, 0.8104, 1.2504]])


In [23]:
## 就地相加
## 将x相加给y
y.add_(x)
print(y)

tensor([[1.1852, 1.0870, 0.7054],
        [0.5820, 1.3569, 0.4054],
        [0.6848, 1.4990, 0.5285],
        [1.5548, 1.0458, 0.8686],
        [1.0402, 0.8104, 1.2504]])


In [27]:
## 索引 x的第二列
print(x[:,1])

tensor([0.8427, 0.4661, 0.6920, 0.2325, 0.4009])


In [34]:
## 使用torch.view调整大小/重塑张量
x=torch.randn(4,4)
y=x.view(16)
z=x.view(-1,8)
print(x.size(),y.size(),z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [35]:
## 使用.item()获取张量的数字
x=torch.randn(1)
print(x)
print(x.item())

tensor([0.5832])
0.5832415819168091


## NumPy
### 将张量转为NumPy 数组

In [36]:
a=torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [37]:
b=a.numpy()
print(b)

[1. 1. 1. 1. 1.]


我们看下numpy数组的值如何变化

In [38]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


### 将NumPy数组转为张量

In [39]:
import numpy as np
a=np.ones(5)
b=torch.from_numpy(a)
np.add(a,1,out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


## CUDA Tensor

In [42]:
if torch.cuda.is_available():
    device=torch.device("cuda")
    y=torch.ones_like(x,device=device)
    x=x.to(device)
    z=x+y
    print(z)
    print(z.to("cpu",torch.double))

tensor([1.5832], device='cuda:0')
tensor([1.5832], dtype=torch.float64)
