## 1 axis=0的时候

In [38]:
import numpy as np
a = np.array([[1, 2, 3], [1, 2, 3], [1, 2, 3]])
b = np.array([[4, 5, 6], [4, 5, 6], [4, 5, 6]])
c = np.stack((a, b), axis=0)
c

array([[[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]],

       [[4, 5, 6],
        [4, 5, 6],
        [4, 5, 6]]])

In [39]:
a.shape,c.shape

((3, 3), (2, 3, 3))

c的每个轴的维度为2,3,3，至于这里c的维度为什么变成2,3,3，可以了解下stack，这里2相当于最外层的[]里面变成两个元素，一个是a，一个是b

In [40]:
c[:,:,:]

array([[[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]],

       [[4, 5, 6],
        [4, 5, 6],
        [4, 5, 6]]])

上面是每个轴取全部元素

In [41]:
c[1:2,:2,:]

array([[[4, 5, 6],
        [4, 5, 6]]])

`c[1:2,:2,:]`也等同于`c[1,:2,:]`,取第1个轴的第二个元素，取第2个轴的前两个元素，取第3个轴的全部元素

In [42]:
c[0,:,:]

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

`c[0,:,:]`等同于`c[0]`，取第1个轴的全部元素，其他取全部

In [43]:
c[0]

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

## 2 axis=1的时候

In [45]:
import numpy as np
a = np.array([[1, 2, 3], [1, 2, 3], [1, 2, 3]])
b = np.array([[4, 5, 6], [4, 5, 6], [4, 5, 6]])
c = np.stack((a, b), axis=1)
c

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

![](http://wx4.sinaimg.cn/mw690/af2d2659ly1fmxw587oboj20hb0brgli.jpg)

## 3 axis=2的时候

In [46]:
import numpy as np
a = np.array([[1, 2, 3], [1, 2, 3], [1, 2, 3]])
b = np.array([[4, 5, 6], [4, 5, 6], [4, 5, 6]])
c = np.stack((a, b), axis=2)
c

array([[[1, 4],
        [2, 5],
        [3, 6]],

       [[1, 4],
        [2, 5],
        [3, 6]],

       [[1, 4],
        [2, 5],
        [3, 6]]])

![](http://wx1.sinaimg.cn/mw690/af2d2659ly1fmxw58osmzj20fm0c6mx2.jpg)

reference：https://blog.csdn.net/qq_17550379/article/details/78934529