In [3]:
#导入需要的模块
import numpy as np
from numpy import genfromtxt

In [48]:
#加载数据
dataPath="files\data\house.csv"
dataSet=genfromtxt(dataPath,delimiter=',')
dataSet

array([[ 1.1,  1.5,  2.5],
       [ 1.3,  1.9,  3.2],
       [ 1.5,  2.3,  3.9],
       [ 1.7,  2.7,  4.6],
       [ 1.9,  3.1,  5.3],
       [ 2.1,  3.5,  6. ],
       [ 2.3,  3.9,  6.7],
       [ 2.5,  4.3,  7.4],
       [ 2.7,  4.7,  8.1],
       [ 2.9,  5.1,  8.8]])

In [50]:
#将数据分成自变量和因变量矩阵
def getData(dataSet):
    m,n=np.shape(dataSet)
    trainData=np.ones((m,n))
    trainData[:,:-1]=dataSet[:,:-1]
    trainLabel=dataSet[:,-1]
    return trainData,trainLabel

In [51]:
#实现批处理梯度下降算法
def batchGradientDescent(x, y, theta, alpha, m, maxIterations):
    xTrains = x.transpose()
    for i in range(0, maxIterations):
        hypothesis = np.dot(x, theta)
        loss = hypothesis - y
        gradient = np.dot(xTrains, loss) / m
        theta = theta - alpha * gradient
    return theta

In [58]:
#初始化参数
trainData, trainLabel = getData(dataSet)
print(trainData,trainLabel)
m, n = np.shape(trainData)
theta = np.ones(n)
alpha = 0.05
maxIteration = 1000

[[ 1.1  1.5  1. ]
 [ 1.3  1.9  1. ]
 [ 1.5  2.3  1. ]
 [ 1.7  2.7  1. ]
 [ 1.9  3.1  1. ]
 [ 2.1  3.5  1. ]
 [ 2.3  3.9  1. ]
 [ 2.5  4.3  1. ]
 [ 2.7  4.7  1. ]
 [ 2.9  5.1  1. ]] [ 2.5  3.2  3.9  4.6  5.3  6.   6.7  7.4  8.1  8.8]


In [57]:
theta = batchGradientDescent(trainData, trainLabel, theta, alpha, m, maxIteration)
theta 

array([ 0.71493625,  1.39253188, -0.37522769])

In [54]:
#预测函数
def predict(x, theta):
    m, n = np.shape(x)
    xTest = np.ones((m, n+1))
    xTest[:, :-1] = x
    yPre = np.dot(xTest, theta)
    return yPre

In [55]:
x = np.array([[3.1, 5.5], [3.3, 5.9], [3.5, 6.3], [3.7, 6.7], [3.9, 7.1]])
print(predict(x, theta)) 

[  9.49608552  10.19523475  10.89438398  11.59353321  12.29268244]


In [56]:
import numpy as np
import random
from numpy import genfromtxt

def getData(dataSet):
    m, n = np.shape(dataSet)
    trainData = np.ones((m, n))
    trainData[:,:-1] = dataSet[:,:-1]
    trainLabel = dataSet[:,-1]
    return trainData, trainLabel

def batchGradientDescent(x, y, theta, alpha, m, maxIterations):
    xTrains = x.transpose()
    for i in range(0, maxIterations):
        hypothesis = np.dot(x, theta)
        loss = hypothesis - y
        # print loss
        gradient = np.dot(xTrains, loss) / m
        theta = theta - alpha * gradient
    return theta

def predict(x, theta):
    m, n = np.shape(x)
    xTest = np.ones((m, n+1))
    xTest[:, :-1] = x
    yP = np.dot(xTest, theta)
    return yP

dataPath = "files\data\house.csv"
dataSet = genfromtxt(dataPath, delimiter=',')
trainData, trainLabel = getData(dataSet)
m, n = np.shape(trainData)
theta = np.ones(n)
alpha = 0.1
maxIteration = 5000
theta = batchGradientDescent(trainData, trainLabel, theta, alpha, m, maxIteration)
x = np.array([[3.1, 5.5], [3.3, 5.9], [3.5, 6.3], [3.7, 6.7], [3.9, 7.1]])
print(predict(x, theta))

[  9.5  10.2  10.9  11.6  12.3]
