# 练习题解答

- 当 x=0 时，

R(δ 1 |x = 0) = −80 × 0.3 − 20 × 0.6 + 10 × 0.7 = −29

R(δ 2 |x = 0) = −40 × 0.3 − 10 × 0.6 − 5 × 0.7 = −21.5

在 x=0 时，最小风险对应决策为转让专利。

- 在 x=1 时，

R(δ 1 |x = 1) = −80 × 0.7 − 20 × 0.4 + 10 × 0.3 = −61

R(δ 2 |x = 1) = −40 × 0.7 − 10 × 0.4 − 5 × 0.3 = −33.5

在 x=1 时，最小风险对应决策为转让专利。

## 作业一
![](https://ws1.sinaimg.cn/large/e59539f0ly1fpn5caxt79j20md0fon0q.jpg)

## 问题1 

In [2]:
import pandas as pd

In [18]:
data=pd.read_csv('files/data/python48-data/iris.csv')
print(data.shape)
w1=data[data['Species']=='versicolor']
w2=data[data['Species']=='virginica']
x1=w1['Petal.Length'].mean()
var1=w1['Petal.Length'].var()
x2=w2['Petal.Length'].mean()
var2=w2['Petal.Length'].var()
print("w1的期望和方差的极大似然估计为：",x1,var1)
print("w2的期望和方差的极大似然估计为：",x2,var2)

(150, 6)
w1的期望和方差的极大似然估计为： 4.26 0.22081632653061237
w2的期望和方差的极大似然估计为： 5.552 0.304587755102041


In [9]:
w1[w1['Petal.Length']==5.0]

id  Sepal.Length  Sepal.Width  Petal.Length  Petal.Width     Species
77  78           6.7          3.0           5.0          1.7  versicolor

In [6]:
w2[w2['Petal.Length']==5.0]

id  Sepal.Length  Sepal.Width  Petal.Length  Petal.Width    Species
113  114           5.7          2.5           5.0          2.0  virginica
119  120           6.0          2.2           5.0          1.5  virginica
146  147           6.3          2.5           5.0          1.9  virginica

根据密度分布最大原则，因为Petal.length出现的为5次数，w2>w1,所以x=5.0的判别类别为virginica

## 问题2

In [21]:
P_w1,P_w2=0.3,0.7
R_w1=P_w1*0+P_w2*3
R_w2=P_w2*1+P_w1*0
print(R_w1,R_w2) 

2.0999999999999996 0.7


根据期望损失最小原则，最优决策是w2

In [54]:
com_data=data[data['Species']!='setosa']
com_data=com_data.sort_values(['Petal.Length'])
com_data[['Petal.Length','Species']][29:30]

Petal.Length     Species
68           4.5  versicolor

分界点估计为4.5,当Petal.Length小于4.5时，判别为第一类versicolor，否则判别为第二类virginica

## 问题3

# 1 数据集简介
```iris以鸢尾花的特征作为数据来源，常用在分类操作中。该数据集由3种不同类型的鸢尾花的50个样本数据构成。其中的一个种类与另外两个种类是线性可分离的，后两个种类是非线性可分离的。```

该数据集包含了5个属性：
- Sepal.Length（花萼长度），单位是cm;
- Sepal.Width（花萼宽度），单位是cm;
- Petal.Length（花瓣长度），单位是cm;
- Petal.Width（花瓣宽度），单位是cm;
- 种类：Iris Setosa（山鸢尾）、Iris Versicolour（杂色鸢尾），以及Iris Virginica（维吉尼亚鸢尾）。

## 2 sklearn实现决策树


In [3]:
from sklearn import tree
feature=[[140,1],[130,1],[150,0],[170,0]]
labels=[0,0,1,1]
clf=tree.DecisionTreeClassifier()
clf=clf.fit(feature,labels)
print(clf.predict([[150,0]]))

[1]


## 3 使用鸢尾花训练决策树

In [4]:
import numpy as np
from sklearn.datasets import load_iris
from sklearn import tree

### 3.1 引入数据集

In [5]:
iris=load_iris()
for key in iris:
    print(key)

data
target
target_names
DESCR
feature_names


In [6]:
print(iris['data'][:5],iris['target'][:5],iris['target_names'])

[[ 5.1  3.5  1.4  0.2]
 [ 4.9  3.   1.4  0.2]
 [ 4.7  3.2  1.3  0.2]
 [ 4.6  3.1  1.5  0.2]
 [ 5.   3.6  1.4  0.2]] [0 0 0 0 0] ['setosa' 'versicolor' 'virginica']


In [7]:
test_idx=[0,50,100]

### 3.2 训练集 和 测试集 

In [8]:
# training data
train_target=np.delete(iris.target,test_idx)
train_data=np.delete(iris.data,test_idx,axis=0)

In [9]:
# testing data
test_target=iris.target[test_idx]
test_data=iris.data[test_idx]

clf=tree.DecisionTreeClassifier()
clf=clf.fit(train_data,train_target)

print(test_target)
print(clf.predict(test_data))

[0 1 2]
[0 1 2]


## 4 code可视化 制作一个简易可读的PDF

In [11]:
# http://www.bubuko.com/infodetail-1778859.html
# https://www.cnblogs.com/iamxyq/p/5918611.html
from sklearn.externals.six import StringIO    
import pydotplus   
dot_data = StringIO()   
tree.export_graphviz(clf, out_file=dot_data,  
                      feature_names=iris.feature_names,    
                         class_names=iris.target_names,    
                         filled=True, rounded=True,    
                         special_characters=True)   
graph = pydotplus.graph_from_dot_data(dot_data.getvalue())   
# graph.write_pdf("iris.pdf")  
graph.write_png('iris.png') 

True

![](https://ws1.sinaimg.cn/large/e59539f0ly1fpjtrw3pg9j20wr0ovwhl.jpg)