# [参考 ](https://docs.scipy.org/doc/numpy-dev/user/quickstart.html)
```NumPy的主要对象是具有相同数据类型数据的多维数组。它是一个含有相同数据（通常为数字）类型的表，这些有一组整数来标注索引。
NumPy的维称作成轴(axis)，轴的个数叫做行(rank)。比如：
[1, 2, 1]
轴的个数为1，行(rank)就是1

[[ 1., 0., 0.],
[ 0., 1., 2.]] 
上面这个数组有2行(也就是它是2维的)，第一位维度的长度为2（也就是2行），第二维度的长度为3（也就是3列）
 ```

```
NumPy的数组类叫作ndarray。下面是ndarray的几个重要属性
ndarray.ndim:数组的轴的个数（就是维数）
ndarray.shape:数组的维度(是一个元组)。比如矩阵有n行m列，那么shape为（n,m）
ndarray.size:数组元素的个数。也是shape(n,m)元素的乘积
ndarray.dtype:数组元素类型的描述。例如：numpy.int32, numpy.int16, and numpy.float64 
ndarray.itemsize:数组每个元素的字节大小。对于类型为floa64的元素，itemsize为8（=64/8，1byte=8bit）
ndarray.data:数组的缓存数据。通常情况下通过索引获取数据，不必要使用这个属性
```

# 快速入门实例

In [1]:
import numpy  as np
a=np.arange(15)
b=a.reshape(3,5)
print(a)
print(b)
print("b.shape=",b.shape)
print("b.ndim=",b.ndim)
print("b.dtype.name=",b.dtype.name)
print("b.itemsize=",b.itemsize)
print("b.size=",b.size)
print("b.type=",type(b))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
b.shape= (3, 5)
b.ndim= 2
b.dtype.name= int32
b.itemsize= 4
b.size= 15
b.type= <class 'numpy.ndarray'>


# 创建数组

In [2]:
a=np.array([1,2,3])
print(a,a.dtype)
b=np.array([1,2,3,4,5.0])
print(b.dtype)

[1 2 3] int32
float64


In [3]:
#一个常见错误就是：提供给array的参数是多个数字，而不是包含数字的列表
a=np.array(1,2,3,4)#错误
a=np.array([1,2,3,4])#正确

ValueError: only 2 non-keyword arguments accepted

In [4]:
#创建多维数组
b=np.array([(1,2,3,5),(4,5,6)])
b

array([(1, 2, 3, 5), (4, 5, 6)], dtype=object)

In [5]:
#创建数组的时候，可以声明数组的数据类型
c=np.array([[1,2],[3,4]],dtype=complex)
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

关于：zeros,ones、empty
zeros()：创建元素全为0的数组
ones()：创建元素全为1的数组
empty():创建随机元素的数组，默认数据类型为float64

In [6]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [7]:
np.ones((2,3,4),dtype=np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [8]:
np.empty((5,6))

array([[3.75921675e-316, 9.58487353e-322, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 5.02034658e+175],
       [4.04186035e-037, 2.72587556e-056, 4.12352216e-061,
        2.05476829e+160, 1.47763641e+248, 1.16096346e-028],
       [7.69165785e+218, 1.35617292e+248, 1.30932099e-071,
        1.61899735e-051, 2.25578622e+180, 4.00073286e+175],
       [4.26397240e-096, 6.32299154e+233, 6.48224638e+170,
        5.22411352e+257, 5.74020278e+180, 8.37174974e-144],
       [1.41529402e+161, 9.16651763e-072, 3.45944511e+097,
        2.21623333e-052, 3.58637636e+126, 1.58268989e-319]])

In [9]:
from numpy import pi
print(np.linspace(0,2,9))#0-2中的9个数字
x=np.linspace(0,2*pi,100)
f=np.sin(x)#f结果集

[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]


打印数组
如果数组元素太多，NumPy就会自动跳过中间部分的元素并且只打印边界元素

In [10]:
print(np.arange(10000))
print(np.arange(10000).reshape(100,100))

[   0    1    2 ... 9997 9998 9999]
[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]


# 基本运算

In [11]:
a=np.array([20,30,40,50])
b=np.arange(4)
c=a-b
print(c)#减
print(b**2)#乘
d=10*np.sin(a)#计算sin函数的结果集
print(d)
print(a<35)
b+=a#加
print(b)

[20 29 38 47]
[0 1 4 9]
[ 9.12945251 -9.88031624  7.4511316  -2.62374854]
[ True  True False False]
[20 31 42 53]


在不同数据类型的数组计算过程中，结果的数据类型自动变为精度更高的数据类型

In [12]:
a=np.ones(3,dtype=np.int32)
b=np.linspace(0,np.pi,3)
print(b.dtype.name)
c=a+b
print(c,c.dtype.name)
d=np.exp(c*1j)
print(d,d.dtype.name)

float64
[1.         2.57079633 4.14159265] float64
[ 0.54030231+0.84147098j -0.84147098+0.54030231j -0.54030231-0.84147098j] complex128


ndarray这个类有很多对数组的一元操作，比如计算整个数组的所有元素的和

In [13]:
a=np.random.random((2,3))
print(a)
print(a.sum())
print(a.min())
print(a.max())

[[0.18975279 0.56613643 0.47077784]
 [0.44095475 0.13323983 0.57282698]]
2.3736886161127395
0.13323983169400022
0.5728269809733358


可以按轴计算结果，比如下面

In [14]:
b=np.arange(12).reshape(3,4)
print(b)
print(b.sum(axis=1))#计算机每一行的和
print(b.sum(axis=0))#计算每一列的和
print(b.cumsum(axis=1))#计算每一行的累积和（对于第一行，0，0+1=1,1+2=3,3+3=6）

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 6 22 38]
[12 15 18 21]
[[ 0  1  3  6]
 [ 4  9 15 22]
 [ 8 17 27 38]]


# 通用函数

In [15]:
B=np.arange(3)#生成[0,1,2]数组
print(B)
print(np.exp(B))#计算机e的幂
print(np.sqrt(B))#计算机每个元素的平方根
C=np.array([2.,-1.,4.])
print(np.add(B,C))

[0 1 2]
[1.         2.71828183 7.3890561 ]
[0.         1.         1.41421356]
[2. 0. 6.]


In [16]:
import numpy as np

#Input array
X=np.array([[1,0,1,0],[1,0,1,1],[0,1,0,1]])

#Output
y=np.array([[1],[1],[0]])

#Sigmoid Function
def sigmoid (x):
    return 1/(1 + np.exp(-x))

#Derivative of Sigmoid Function
def derivatives_sigmoid(x):
    return x * (1 - x)

#Variable initialization
epoch=5000 #Setting training iterations
lr=0.1 #Setting learning rate
inputlayer_neurons = X.shape[1] #number of features in data set
hiddenlayer_neurons = 3 #number of hidden layers neurons
output_neurons = 1 #number of neurons at output layer

#weight and bias initialization
wh=np.random.uniform(size=(inputlayer_neurons,hiddenlayer_neurons))
bh=np.random.uniform(size=(1,hiddenlayer_neurons))
wout=np.random.uniform(size=(hiddenlayer_neurons,output_neurons))
bout=np.random.uniform(size=(1,output_neurons))

for i in range(epoch):
    #Forward Propogation
    hidden_layer_input1=np.dot(X,wh)
    hidden_layer_input=hidden_layer_input1 + bh
    hiddenlayer_activations = sigmoid(hidden_layer_input)
    output_layer_input1=np.dot(hiddenlayer_activations,wout)
    output_layer_input= output_layer_input1+ bout
    output = sigmoid(output_layer_input)

    #Backpropagation
    E = y-output
    slope_output_layer = derivatives_sigmoid(output)
    slope_hidden_layer = derivatives_sigmoid(hiddenlayer_activations)
    d_output = E * slope_output_layer
    Error_at_hidden_layer = d_output.dot(wout.T)
    d_hiddenlayer = Error_at_hidden_layer * slope_hidden_layer
    wout += hiddenlayer_activations.T.dot(d_output) *lr
    bout += np.sum(d_output, axis=0,keepdims=True) *lr
    wh += X.T.dot(d_hiddenlayer) *lr
    bh += np.sum(d_hiddenlayer, axis=0,keepdims=True) *lr
print(output)
print(bh)
print(wh)

[[0.97812517]
 [0.97012536]
 [0.03980562]]
[[-0.09154642  0.05763739 -0.31849807]]
[[-0.80319518  0.94813082  1.87201692]
 [ 1.66276194  0.45541713 -2.00078828]
 [-1.12021938  0.44848649  2.27630446]
 [ 0.48444545  0.51631078 -0.90395865]]


# 索引、切片、递归

In [17]:
a=np.arange(10)**3
print(a)
print(a[2:5])
a[:6:2]=-1000#0-6之间的元素，每两个元素，第二个等于-1000
print(a)
print(a[::-1])#翻转元素

[  0   1   8  27  64 125 216 343 512 729]
[ 8 27 64]
[-1000     1 -1000    27 -1000   125   216   343   512   729]
[  729   512   343   216   125 -1000    27 -1000     1 -1000]


In [18]:
#多维数组
def f(x,y):
    return 10*x+y
b=np.fromfunction(f,(5,4),dtype=int)
print(b)
print(b[2,3])
print(b[0:5,1])
print(b[:,1])
print(b[1:3,:])#在第2行和第3行的每一列元素

[[ 0  1  2  3]
 [10 11 12 13]
 [20 21 22 23]
 [30 31 32 33]
 [40 41 42 43]]
23
[ 1 11 21 31 41]
[ 1 11 21 31 41]
[[10 11 12 13]
 [20 21 22 23]]


# 形状操作


In [19]:
a=np.floor(10*np.random.random((3,4)))#向下取整
print(a)
print(a.shape)

[[9. 3. 9. 8.]
 [3. 8. 2. 3.]
 [7. 3. 0. 2.]]
(3, 4)


一个数组的形状可以使用多种命令去改变。

In [20]:
print(a.ravel())#返回一个平铺的数组
print(a.reshape(6,2))#重新改变形状

[9. 3. 9. 8. 3. 8. 2. 3. 7. 3. 0. 2.]
[[9. 3.]
 [9. 8.]
 [3. 8.]
 [2. 3.]
 [7. 3.]
 [0. 2.]]


In [21]:
z=np.arange(16).reshape(4,4)
z

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [22]:
z.shape

(4, 4)

In [29]:
z.reshape(-1) # 一行

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [30]:
z.reshape(1,-1) # 一行

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]])

In [26]:
z.reshape(-1,1) # 一列

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15]])

In [27]:
z.reshape(2,-1) # 不管有多少列，只要保证为两行

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [28]:
z.reshape(-1,2) # 不管有多少行，只要保证为2列

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15]])