# 1 Tensors

In [10]:
import torch
# exp1 :construct a 5x3 matrix, uninitialized:
x=torch.empty(5,3)
print(x)

tensor(1.00000e-04 *
       [[ 0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.0000,  5.2658,  0.0000]])


In [11]:

# exp2:construct a randomly initialized matrix:
x=torch.rand(5,3)
print(x)

tensor([[ 0.1889,  0.7574,  0.5933],
        [ 0.6637,  0.3017,  0.6300],
        [ 0.5849,  0.9983,  0.2892],
        [ 0.8989,  0.5606,  0.2526],
        [ 0.4713,  0.3371,  0.0223]])


In [12]:
# exp3:construct a matrix filled zeros and of dtype long
x=torch.zeros(5,3,dtype=torch.long)
print(x)

tensor([[ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0]])


In [13]:
# exp4:construct a tensor directly from data:
x=torch.tensor([5.5,3])
print(x)

tensor([ 5.5000,  3.0000])


In [14]:
# exp5：or create a tensor based on an existing tensor.
# These methods will reuse properties of the input tensor, e.g. dtype,
# unless new values are provided by user
x=x.new_ones(5,3,dtype=torch.double)    # new_* methods take in sizes
print(x)

x=torch.rand_like(x,dtype=torch.float)   # new_* methods take in sizes
print(x)    # new_* methods take in sizes


tensor([[ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.]], dtype=torch.float64)
tensor([[ 0.1537,  0.1490,  0.7924],
        [ 0.5670,  0.0083,  0.7103],
        [ 0.6024,  0.6682,  0.4202],
        [ 0.3626,  0.1101,  0.3646],
        [ 0.5865,  0.7689,  0.1638]])


In [15]:
# get its size:
print(x.size())

torch.Size([5, 3])


# 2 Operations

## 2.1 Addition: syntax 1

In [18]:
y=torch.rand(5,3)
print(x+y)

tensor([[ 0.2149,  0.3175,  1.2217],
        [ 0.6788,  0.8254,  0.9440],
        [ 1.0197,  1.0750,  1.3813],
        [ 0.5985,  1.0242,  0.4603],
        [ 1.4570,  1.6293,  0.3178]])


## 2.2 Addition: syntax 2

In [19]:
print(torch.add(x,y))

tensor([[ 0.2149,  0.3175,  1.2217],
        [ 0.6788,  0.8254,  0.9440],
        [ 1.0197,  1.0750,  1.3813],
        [ 0.5985,  1.0242,  0.4603],
        [ 1.4570,  1.6293,  0.3178]])


## 2.3 Addition: providing an output tensor as argument

In [20]:
result=torch.empty(5,3)
torch.add(x,y,out=result)
print(result)

tensor([[ 0.2149,  0.3175,  1.2217],
        [ 0.6788,  0.8254,  0.9440],
        [ 1.0197,  1.0750,  1.3813],
        [ 0.5985,  1.0242,  0.4603],
        [ 1.4570,  1.6293,  0.3178]])


## 2.5 Addition: in-place

In [21]:
# add x to y
y.add_(x)

tensor([[ 0.2149,  0.3175,  1.2217],
        [ 0.6788,  0.8254,  0.9440],
        [ 1.0197,  1.0750,  1.3813],
        [ 0.5985,  1.0242,  0.4603],
        [ 1.4570,  1.6293,  0.3178]])

## 2.5 Indexing

In [22]:
x

tensor([[ 0.1537,  0.1490,  0.7924],
        [ 0.5670,  0.0083,  0.7103],
        [ 0.6024,  0.6682,  0.4202],
        [ 0.3626,  0.1101,  0.3646],
        [ 0.5865,  0.7689,  0.1638]])

In [28]:
x[:,1] # 选取第二列

tensor([ 0.1490,  0.0083,  0.6682,  0.1101,  0.7689])

## 2.5 Resizing

In [34]:
x=torch.randn(4,4)
x

tensor([[-0.7407,  1.8183,  0.9411, -0.0961],
        [-1.7284, -1.2689, -0.0478, -0.3334],
        [ 0.3571,  0.1362, -1.3795,  1.3553],
        [-0.7430,  0.4966,  0.5907,  1.0943]])

In [33]:
y=x.view(16)
y

tensor([-2.3152, -1.0368, -0.0738,  0.9901, -0.4519, -0.1859,  1.2947,
        -1.2782,  0.2498, -2.3731, -0.3418, -0.3598,  2.2147, -0.7491,
         1.0235, -0.5832])

In [35]:
z=x.view(-1,8) # the size -1 is inferred from other dimensions
z

tensor([[-0.7407,  1.8183,  0.9411, -0.0961, -1.7284, -1.2689, -0.0478,
         -0.3334],
        [ 0.3571,  0.1362, -1.3795,  1.3553, -0.7430,  0.4966,  0.5907,
          1.0943]])

In [36]:
z=x.view(8,-1) # the size -1 is inferred from other dimensions
z

tensor([[-0.7407,  1.8183],
        [ 0.9411, -0.0961],
        [-1.7284, -1.2689],
        [-0.0478, -0.3334],
        [ 0.3571,  0.1362],
        [-1.3795,  1.3553],
        [-0.7430,  0.4966],
        [ 0.5907,  1.0943]])

In [38]:
# If you have a one element tensor, use .item() to get the value as a Python number
x=torch.randn(1)
print(x)
print(x.item())

tensor([-0.3050])
-0.30500277876853943


# 3 NumPy Bridge

## 3.1 Converting a Torch Tensor to a NumPy Array

In [41]:
a=torch.ones(5)
print(a)

tensor([ 1.,  1.,  1.,  1.,  1.])


In [42]:
b=a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [43]:
# See how the numpy array changed in value.
a.add_(1)
print(a)
print(b)

tensor([ 2.,  2.,  2.,  2.,  2.])
[2. 2. 2. 2. 2.]


In [44]:
## 3.2 Converting NumPy Array to Torch Tensor
import numpy as np
a=np.ones(5)
b=torch.from_numpy(a)
np.add(a,1,out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([ 2.,  2.,  2.,  2.,  2.], dtype=torch.float64)
