In [1]:
#参考：
#https://jizhi.im/blog/post/10min2pandas01
#http://pandas.pydata.org/pandas-docs/stable/10min.html

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
#创建一个Series对象：传递一个数值列表作为参数，令Pandas使用默认索引
s=pd.Series([1,3,5,np.nan,6,8])
print(s)

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64


In [2]:
#创建一个DataFrame对象:传递datetime索引和列表签的Numpy数组作为参数
#首先创建一个时间序列
dates=pd.date_range('20130101',periods=6)
print(dates)
#创建DataFrame对象，指定index和columns标签
df=pd.DataFrame(np.random.randn(6,4),index=dates,columns=list('ABCD'))
print(df)

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')
                   A         B         C         D
2013-01-01 -1.270863  1.064493 -0.248180  2.641848
2013-01-02  1.601009  0.972228 -1.226009  0.297383
2013-01-03 -0.065541 -0.527363  0.621653 -0.888621
2013-01-04  2.120578  0.746746  0.987866 -0.464909
2013-01-05  1.195726  0.906736 -0.241997  0.596301
2013-01-06  0.647681  0.287157  0.058569 -0.961831


In [18]:
#观察数据
#查看一个DataFrame对象的前几行和最后几行
print(df.head())
print(df.tail(3))
#默认情况下 .head()和.tail()输出首尾的前5行，也可以指定输出行数

                   A         B         C         D
2013-01-01 -0.507607 -0.945963 -0.211500 -0.354067
2013-01-02  0.381946  0.792727 -1.034413  1.477787
2013-01-03 -1.425695  0.870290 -1.130122  0.197742
2013-01-04 -0.118737 -1.154083  0.801030 -0.800898
2013-01-05 -0.894219 -1.018270 -1.300875  0.260018
                   A         B         C         D
2013-01-04 -0.118737 -1.154083  0.801030 -0.800898
2013-01-05 -0.894219 -1.018270 -1.300875  0.260018
2013-01-06  2.511568 -0.507313  0.071194 -0.658921


In [23]:
#查看索引
print(df.index)
#列表签
print(df.columns)
#数值
print(df.values)
#统计
print(df.describe())

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')
Index(['A', 'B', 'C', 'D'], dtype='object')
[[-0.50760718 -0.94596278 -0.21149994 -0.3540674 ]
 [ 0.38194596  0.79272681 -1.03441257  1.47778738]
 [-1.42569506  0.87029035 -1.13012242  0.19774176]
 [-0.11873718 -1.15408285  0.80102985 -0.8008982 ]
 [-0.89421889 -1.01827023 -1.30087514  0.26001845]
 [ 2.51156848 -0.50731273  0.07119421 -0.65892141]]
              A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean  -0.008791 -0.327102 -0.467448  0.020277
std    1.382562  0.923563  0.827027  0.835354
min   -1.425695 -1.154083 -1.300875 -0.800898
25%   -0.797566 -1.000193 -1.106195 -0.582708
50%   -0.313172 -0.726638 -0.622956 -0.078163
75%    0.256775  0.467717  0.000521  0.244449
max    2.511568  0.870290  0.801030  1.477787


In [28]:
# 灵活调教你的DataFrame
#转置
print(df.T)
#按列排序，逐步递减
print(df.sort_index(axis=1,ascending=False))
#按值排序，‘B’列逐行递增
print(df.sort_values(by='B'))

   2013-01-01  2013-01-02  2013-01-03  2013-01-04  2013-01-05  2013-01-06
A   -0.507607    0.381946   -1.425695   -0.118737   -0.894219    2.511568
B   -0.945963    0.792727    0.870290   -1.154083   -1.018270   -0.507313
C   -0.211500   -1.034413   -1.130122    0.801030   -1.300875    0.071194
D   -0.354067    1.477787    0.197742   -0.800898    0.260018   -0.658921
                   D         C         B         A
2013-01-01 -0.354067 -0.211500 -0.945963 -0.507607
2013-01-02  1.477787 -1.034413  0.792727  0.381946
2013-01-03  0.197742 -1.130122  0.870290 -1.425695
2013-01-04 -0.800898  0.801030 -1.154083 -0.118737
2013-01-05  0.260018 -1.300875 -1.018270 -0.894219
2013-01-06 -0.658921  0.071194 -0.507313  2.511568
                   A         B         C         D
2013-01-04 -0.118737 -1.154083  0.801030 -0.800898
2013-01-05 -0.894219 -1.018270 -1.300875  0.260018
2013-01-01 -0.507607 -0.945963 -0.211500 -0.354067
2013-01-06  2.511568 -0.507313  0.071194 -0.658921
2013-01-02  0.3819

In [35]:
#选中
#获取
print(df["A"])#与df.A相同
print(df.A)
#使用[]分割DataFrame
print(df[0:3])
print(df['20130102':'20130104'])

2013-01-01   -0.507607
2013-01-02    0.381946
2013-01-03   -1.425695
2013-01-04   -0.118737
2013-01-05   -0.894219
2013-01-06    2.511568
Freq: D, Name: A, dtype: float64
2013-01-01   -0.507607
2013-01-02    0.381946
2013-01-03   -1.425695
2013-01-04   -0.118737
2013-01-05   -0.894219
2013-01-06    2.511568
Freq: D, Name: A, dtype: float64
                   A         B         C         D
2013-01-01 -0.507607 -0.945963 -0.211500 -0.354067
2013-01-02  0.381946  0.792727 -1.034413  1.477787
2013-01-03 -1.425695  0.870290 -1.130122  0.197742
                   A         B         C         D
2013-01-02  0.381946  0.792727 -1.034413  1.477787
2013-01-03 -1.425695  0.870290 -1.130122  0.197742
2013-01-04 -0.118737 -1.154083  0.801030 -0.800898


In [4]:
#按标签选择
#选中一行
print(df.loc(dates[0]))
#标签选中复制数列（所有行，输出只显示前5行）
print(df.loc[:,['A','B']])
#行，列同时切分（包括起止点）
print(df.loc['20130102':'20130104',['A','B']])
#返回一个元素（两种等效）
print(df.loc[dates[0],'A'])
print(df.at[dates[0],'A'])

                   A         B
2013-01-01 -1.270863  1.064493
2013-01-02  1.601009  0.972228
2013-01-03 -0.065541 -0.527363
2013-01-04  2.120578  0.746746
2013-01-05  1.195726  0.906736
2013-01-06  0.647681  0.287157
                   A         B
2013-01-02  1.601009  0.972228
2013-01-03 -0.065541 -0.527363
2013-01-04  2.120578  0.746746
-1.27086342455
-1.27086342455
