# [参考 ](https://docs.scipy.org/doc/numpy-dev/user/quickstart.html)
```NumPy的主要对象是具有相同数据类型数据的多维数组。它是一个含有相同数据（通常为数字）类型的表，这些有一组整数来标注索引。
NumPy的维称作成轴(axis)，轴的个数叫做行(rank)。比如：
[1, 2, 1]
轴的个数为1，行(rank)就是1

[[ 1., 0., 0.],
[ 0., 1., 2.]] 
上面这个数组有2行(也就是它是2维的)，第一位维度的长度为2（也就是2行），第二维度的长度为3（也就是3列）
 ```

```
NumPy的数组类叫作ndarray。下面是ndarray的几个重要属性
ndarray.ndim:数组的轴的个数（就是维数）
ndarray.shape:数组的维度(是一个元组)。比如矩阵有n行m列，那么shape为（n,m）
ndarray.size:数组元素的个数。也是shape(n,m)元素的乘积
ndarray.dtype:数组元素类型的描述。例如：numpy.int32, numpy.int16, and numpy.float64 
ndarray.itemsize:数组每个元素的字节大小。对于类型为floa64的元素，itemsize为8（=64/8，1byte=8bit）
ndarray.data:数组的缓存数据。通常情况下通过索引获取数据，不必要使用这个属性
```

# 快速入门实例

In [1]:
import numpy  as np
a=np.arange(15)
b=a.reshape(3,5)
print(a)
print(b)
print("b.shape=",b.shape)
print("b.ndim=",b.ndim)
print("b.dtype.name=",b.dtype.name)
print("b.itemsize=",b.itemsize)
print("b.size=",b.size)
print("b.type=",type(b))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
b.shape= (3, 5)
b.ndim= 2
b.dtype.name= int32
b.itemsize= 4
b.size= 15
b.type= <class 'numpy.ndarray'>


# 创建数组

In [2]:
a=np.array([1,2,3])
print(a,a.dtype)
b=np.array([1,2,3,4,5.0])
print(b.dtype)

[1 2 3] int32
float64


In [3]:
#一个常见错误就是：提供给array的参数是多个数字，而不是包含数字的列表
a=np.array(1,2,3,4)#错误
a=np.array([1,2,3,4])#正确

ValueError: only 2 non-keyword arguments accepted

In [4]:
#创建多维数组
b=np.array([(1,2,3,5),(4,5,6)])
b

array([(1, 2, 3, 5), (4, 5, 6)], dtype=object)

In [5]:
#创建数组的时候，可以声明数组的数据类型
c=np.array([[1,2],[3,4]],dtype=complex)
c

array([[ 1.+0.j,  2.+0.j],
       [ 3.+0.j,  4.+0.j]])

关于：zeros,ones、empty
zeros()：创建元素全为0的数组
ones()：创建元素全为1的数组
empty():创建随机元素的数组，默认数据类型为float64

In [6]:
np.zeros((3,4))

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [7]:
np.ones((2,3,4),dtype=np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [8]:
np.empty((5,6))

array([[  2.04748105e+161,   1.81450395e-152,   6.01334515e-154,
          1.32971156e-152,   5.39223091e+241,   1.02189774e-152],
       [  2.85341981e+242,   1.47305454e+171,   6.62278150e+265,
          3.81695140e+180,   2.31463017e-152,   1.35725900e+248],
       [  6.01334515e-154,   1.94860809e-153,   2.41795992e+198,
          7.53046676e+252,   5.98185637e-154,   5.33804097e+184],
       [  3.53185982e+069,   5.70945931e+228,   4.00444531e+252,
          4.73669337e+164,   2.50138310e-091,   1.73354582e+156],
       [  1.27966391e-152,   8.78411349e+247,   6.01347002e-154,
          1.89122289e+219,   1.94255855e+227,   9.75026736e+199]])

In [9]:
from numpy import pi
print(np.linspace(0,2,9))#0-2中的9个数字
x=np.linspace(0,2*pi,100)
f=np.sin(x)#f结果集

[ 0.    0.25  0.5   0.75  1.    1.25  1.5   1.75  2.  ]


打印数组
如果数组元素太多，NumPy就会自动跳过中间部分的元素并且只打印边界元素

In [3]:
print(np.arange(10000))
print(np.arange(10000).reshape(100,100))

[   0    1    2 ..., 9997 9998 9999]
[[   0    1    2 ...,   97   98   99]
 [ 100  101  102 ...,  197  198  199]
 [ 200  201  202 ...,  297  298  299]
 ..., 
 [9700 9701 9702 ..., 9797 9798 9799]
 [9800 9801 9802 ..., 9897 9898 9899]
 [9900 9901 9902 ..., 9997 9998 9999]]


# 基本运算

In [16]:
a=np.array([20,30,40,50])
b=np.arange(4)
c=a-b
print(c)#减
print(b**2)#乘
d=10*np.sin(a)#计算sin函数的结果集
print(d)
print(a<35)
b+=a#加
print(b)

[20 29 38 47]
[0 1 4 9]
[ 9.12945251 -9.88031624  7.4511316  -2.62374854]
[ True  True False False]
[20 31 42 53]


在不同数据类型的数组计算过程中，结果的数据类型自动变为精度更高的数据类型

In [28]:
a=np.ones(3,dtype=np.int32)
b=np.linspace(0,np.pi,3)
print(b.dtype.name)
c=a+b
print(c,c.dtype.name)
d=np.exp(c*1j)
print(d,d.dtype.name)

float64
[ 1.          2.57079633  4.14159265] float64
[ 0.54030231+0.84147098j -0.84147098+0.54030231j -0.54030231-0.84147098j] complex128


ndarray这个类有很多对数组的一元操作，比如计算整个数组的所有元素的和

In [34]:
a=np.random.random((2,3))
print(a)
print(a.sum())
print(a.min())
print(a.max())

[[ 0.96533444  0.2331663   0.46317757]
 [ 0.25404121  0.56727775  0.22520034]]
2.70819761204
0.225200341897
0.965334444201


可以按轴计算结果，比如下面

In [39]:
b=np.arange(12).reshape(3,4)
print(b)
print(b.sum(axis=1))#计算机每一行的和
print(b.sum(axis=0))#计算每一列的和
print(b.cumsum(axis=1))#计算每一行的累积和（对于第一行，0，0+1=1,1+2=3,3+3=6）

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 6 22 38]
[12 15 18 21]
[[ 0  1  3  6]
 [ 4  9 15 22]
 [ 8 17 27 38]]


# 通用函数

In [54]:
B=np.arange(3)#生成[0,1,2]数组
print(B)
print(np.exp(B))#计算机e的幂
print(np.sqrt(B))#计算机每个元素的平方根
C=np.array([2.,-1.,4.])
print(np.add(B,C))

[0 1 2]
[ 1.          2.71828183  7.3890561 ]
[ 0.          1.          1.41421356]
[ 2.  0.  6.]


In [1]:
import numpy as np

#Input array
X=np.array([[1,0,1,0],[1,0,1,1],[0,1,0,1]])

#Output
y=np.array([[1],[1],[0]])

#Sigmoid Function
def sigmoid (x):
    return 1/(1 + np.exp(-x))

#Derivative of Sigmoid Function
def derivatives_sigmoid(x):
    return x * (1 - x)

#Variable initialization
epoch=5000 #Setting training iterations
lr=0.1 #Setting learning rate
inputlayer_neurons = X.shape[1] #number of features in data set
hiddenlayer_neurons = 3 #number of hidden layers neurons
output_neurons = 1 #number of neurons at output layer

#weight and bias initialization
wh=np.random.uniform(size=(inputlayer_neurons,hiddenlayer_neurons))
bh=np.random.uniform(size=(1,hiddenlayer_neurons))
wout=np.random.uniform(size=(hiddenlayer_neurons,output_neurons))
bout=np.random.uniform(size=(1,output_neurons))

for i in range(epoch):
    #Forward Propogation
    hidden_layer_input1=np.dot(X,wh)
    hidden_layer_input=hidden_layer_input1 + bh
    hiddenlayer_activations = sigmoid(hidden_layer_input)
    output_layer_input1=np.dot(hiddenlayer_activations,wout)
    output_layer_input= output_layer_input1+ bout
    output = sigmoid(output_layer_input)

    #Backpropagation
    E = y-output
    slope_output_layer = derivatives_sigmoid(output)
    slope_hidden_layer = derivatives_sigmoid(hiddenlayer_activations)
    d_output = E * slope_output_layer
    Error_at_hidden_layer = d_output.dot(wout.T)
    d_hiddenlayer = Error_at_hidden_layer * slope_hidden_layer
    wout += hiddenlayer_activations.T.dot(d_output) *lr
    bout += np.sum(d_output, axis=0,keepdims=True) *lr
    wh += X.T.dot(d_hiddenlayer) *lr
    bh += np.sum(d_hiddenlayer, axis=0,keepdims=True) *lr
print(output)
print(bh)
print(wh)

[[ 0.97740806]
 [ 0.96858668]
 [ 0.04015431]]
[[ 0.62593387 -0.45678285  0.21140522]]
[[ 0.05174161  2.37799168 -1.12845579]
 [ 1.05145889 -1.8413515   1.14497468]
 [ 0.75070717  2.00957152 -1.09171432]
 [ 0.40149801 -0.92786005  0.49347667]]


# 索引、切片、递归

In [8]:
a=np.arange(10)**3
print(a)
print(a[2:5])
a[:6:2]=-1000#0-6之间的元素，每两个元素，第二个等于-1000
print(a)
print(a[::-1])#翻转元素

[  0   1   8  27  64 125 216 343 512 729]
[ 8 27 64]
[-1000     1 -1000    27 -1000   125   216   343   512   729]
[  729   512   343   216   125 -1000    27 -1000     1 -1000]


In [22]:
#多维数组
def f(x,y):
    return 10*x+y
b=np.fromfunction(f,(5,4),dtype=int)
print(b)
print(b[2,3])
print(b[0:5,1])
print(b[:,1])
print(b[1:3,:])#在第2行和第3行的每一列元素

[[ 0  1  2  3]
 [10 11 12 13]
 [20 21 22 23]
 [30 31 32 33]
 [40 41 42 43]]
23
[ 1 11 21 31 41]
[ 1 11 21 31 41]
[[10 11 12 13]
 [20 21 22 23]]
